# Generated by Django 5.1.2 on 2024-10-12 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0002_waitlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="creation_count",
            field=models.IntegerField(default=0),
        ),
    ]
