# Generated by Django 5.1.2 on 2024-10-13 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0005_organizer_alter_event_organizer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="organized_events",
                to="API.organizer",
            ),
        ),
    ]
