# Generated by Django 5.1.2 on 2024-10-13 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0007_alter_event_organizer_delete_organizer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="organizer",
        ),
    ]
