# Generated by Django 5.1.2 on 2024-10-13 10:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0011_alter_registration_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together={("event", "user")},
        ),
    ]
