# Generated by Django 5.1.2 on 2024-10-14 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0014_registration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="waitlist",
        ),
        migrations.RemoveField(
            model_name="registration",
            name="is_waitlisted",
        ),
        migrations.AlterField(
            model_name="registration",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_register",
                to="API.event",
            ),
        ),
        migrations.AlterField(
            model_name="registration",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_register",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
