# Generated by Django 5.1.2 on 2024-10-14 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0015_remove_event_waitlist_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="registration",
            unique_together=set(),
        ),
    ]
