# Generated by Django 5.1.2 on 2024-10-14 03:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("API", "0016_alter_registration_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="waitlist",
            field=models.ManyToManyField(
                blank=True,
                related_name="waitlisted_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
